### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by repo-atvc** [MarkTuddenham/Orthogonal-Optimisers#1]
Hi, thanks for your interesting work.

It seems that your hyper-parameters (BS=1024, lr=0.01) are not favorable to original SGD. 

![image](https://user-images.githubusercontent.com/107047197/175424977-c9b140c5-7939-4d3f-9929-1cd1076aec51.png)

**Comment by MarkTuddenham** [comment]
Hi, this plot is just an example, although fairly typical; there is a comparison across many more hyper-parameter sets in the paper.

**Comment by repo-atvc** [comment]
Thanks, I will check the details in the paper.
